### ISSUE TITLE
Error : specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter <set-?>

### ISSUE THREAD

**Issue by leandro1995** [CameraKit/camerakit-android#457]
good day to run camera kid in kotlin or in java I get the following error that is this

Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter <set-?>

![screen shot 2018-11-21 at 12 25 31 pm](https://user-images.githubusercontent.com/25448691/48858211-c9b1ad80-ed88-11e8-9583-a14e8ba24b14.png)

I wanted to know if there is a way to solve it because I use an android 8.0.0

**Comment by emersoncloud** [comment]
Hi @leandro1995 that's a bug on our end. It is because `app:camera_flash` is set to `auto` or `torch`, both of which will give that error. We're releasing a patch this week to give a better error output for those settings. 

However `auto` and `torch` will be fully operational in the final v1.0.0 release. Let me know if you have any more issue!
