### ISSUE TITLE
v1.0.0-beta3.11- the front camera

### ISSUE THREAD

**Issue by leandro1995** [CameraKit/camerakit-android#537]
I've been testing camerakit in version 3.11 and I realize that in the version of Android 6 and 5 the front camera fails to select it with a button sometimes it turns all black or does not want to change the camera and that I used the CameraKit.FACING_FRONT with the setFacing and the result is the same I had to use version 3.10 that does not have that problem

**Comment by KaelMa** [comment]
I found the problem is caused by this commit. After I revert it , it works.
<img width="1496" alt="11111" src="https://user-images.githubusercontent.com/8552840/57835513-3e721b80-77f1-11e9-9a03-2bbb66271c6c.png">
<img width="1447" alt="2222" src="https://user-images.githubusercontent.com/8552840/57835516-403bdf00-77f1-11e9-89ff-28ca8b3954e3.png">

**Comment by weeklynote** [comment]
已收到，我会尽快回复你！
                     ——刘劲字
