### ISSUE TITLE
General problems with different device support

### ISSUE THREAD

**Issue by zoltanf** [CameraKit/camerakit-android#67]
First of all, let me start by stating that I really like the library and would like to use it.

The problem is that of the 8 or so devices that I have, the basic functionality is broken on 3 devices. The problem comes down to:
- The preview is deformed. For example on Galaxy Tab 4 with a rear camera, the preview is shown in wrong orientation and also the aspect ratio is somehow "wrong" so the picture looks skewed and stretched out.
- On Galaxy S5 (one of the most used phones) the preview is fine, but when a picture is taken, and I load it in the preview, the picture is rotated by 90 degrees
... etc etc ...

So most problems come down to rotation of the preview or of the taken picture being wrong. Is there some general fix for this, or is the sad state of camera APIs on Android device that we still need for each of this device to include an "if" condition and a fix for a particular model? 
Is there anything we can do to help identify the actual issues for each affected device?

Thank you and please keep up the good work!

**Comment by android-dataticket** [comment]
I actually ended up removing the orientation listener (DisplayOrientationDetector) from CameraView.java and I handle rotation per device with ‘if’ statements

I wouldn’t recommend this as a fix for anyone else, but it works for me since my clients only use a certain specific few Samsung devices and a certain specific LG device.  They are also restricted to taking pictures in landscape mode for some other unrelated reasons, so locking the camera view in 90degree rotate is desirable for my app.
